# Generated by Django 6.0.5 on 2026-05-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('auditorium', 'Аудитория'), ('coworking', 'Коворкинг'), ('cinema', 'Кинозал')], max_length=20, verbose_name='Тип помещения')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('cashless', 'Безналичный расчёт')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('approved', 'Одобрена'), ('completed', 'Завершена')], default='waiting', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
                'ordering': ['-created_at'],
            },
        ),
    ]
